### ISSUE TITLE
On RaspberryPI, FreeDV GUI goes in a locked status when switching off 700C

### ISSUE THREAD

**Issue by UgoPoddine** [drowe67/freedv-gui#126] opened 2021-05-13 14:27 UTC
Hello David,

FreeDV GUI is now much more stable on RaspberryPI3 than it was two years ago, and that's really appreciated.
Also if minor issue, I would like to make you aware of the fact that, on Raspbian 5.10.17-v7+ #1414 (but it's longtime that i's happens), also FreeDV GUI 1.5.3 devel  c93345e crashes (or - better - comes in some kind of neverending loop status) when, after having worked in 700c mode, the "Stop" control key is pushed. 
This happens only on 700C, all other modes can be stopped as expected.
Before pushing "Stop" no issue : you can transmit, receive or going in "analog" mode without problem.
For switching off the FreeDV-gui it's then necessary to kill the process.

As usual, thank-you for your effort
Best 73s
IU1IPB ugo

**Comment by tmiw** [comment] 2021-05-13 16:52
How long do you typically have FreeDV running before you run into the issue? If possible, can you try running it from the terminal (ideally under gdb but just on its own might produce debug output that can help)?

**Comment by UgoPoddine** [comment] 2021-05-13 17:37
Hello Tmiw,

Thank-you for your so fast answer.
The issue happens always and also immediately after the startup of the gui : I start 700C and, I do nothing more, if I push the "stop" the neverending loop starts. It happens since longtime (perhaps one year or more) : I'm usually keep FreeDV up-to date.
At the moment I will attach the log to from the terminal, made starting FreeDV-GUI, starting 700C, doing nothing more, stopping 700C and finally killing the GUI by CTRL+C : if you need the debug, I will do tomorrow :-)

Regards
Ugo

[freedv_debug.log](https://github.com/drowe67/freedv-gui/files/6474104/freedv_debug.log)

**Comment by drowe67** [comment] 2021-05-13 22:35
Hi @UgoPoddine! 

Could you please tell me:
1. Were you using `build_linux.sh` to build freedv-gui?
1. What Git hash of codec2 is being used (just want to confirm its the current master https://github.com/drowe67/codec2/commit/306e424282b0941caf018e408b91e4e3385948d2).

**Comment by drowe67** [comment] 2021-05-13 22:36
@tmiw those internal ALSA messages are so annoying (on all Linux operating systems), I wonder if there is a way to make them quiet?

**Comment by tmiw** [comment] 2021-05-14 01:59
@drowe67, I imagine the messages will be less of an issue once the PulseAudio PR finally gets accepted into PortAudio master.

**Comment by UgoPoddine** [comment] 2021-05-14 06:43
Hello mates,

still belonging to the "no PulseAudio, pure ALSA is good" party,  I can answer as follow :

1) I have used the build_linux.sh script
2) as I wrote in my post, I'm at c93345e  (the last one, I guess), installed two days ago. Please note that the issue is there since several months (probably one year or more) : I have not shared it because I'm using often FreeDV with a home made wrapper on Raspberry

Thank-you
Ugo

**Comment by UgoPoddine** [comment] 2021-05-14 06:44
Sorry : CODEC2 is at 306e424

U

**Comment by drowe67** [comment] 2021-05-14 08:07
I just tried freedv-gui/master on a Pi 3B and repeated the problem (Stop doesn't work in 700C mode) when freedv-gui is listening to off air noise (no valid signal). I connected it up to my IC7200 and configured to single card RX only. It seemed to run OK apart from that. 

I measured the CPU:

| mode | "Acquisition" CPU load % | Decode CPU load % |
| --- | --- | --- |
| 1600 | 65 | |
| 700C | 148 | 76 |
| 700D | 89 | |
| 700E | 90 | |

So it looks like the 700C modem uses > 100% of CPU during "acquisition" (i.e. looking for a FreeDV signal).  This is a bit odd, as when I try the command line decoder on the same Pi it runs much faster than real time:
```
time ./src/freedv_tx 700C ../../wav/ve9qrp_700d.wav /dev/null
real	0m7.611s
user	0m7.595s
sys	0m0.011s
```
That's a 112 second sample, so 7.6/112 = 7% CPU.  Note I fed it a 700D sample file to make sure it doesn't sync and stays in the worst case, acquisition mode (I just needed a non-700C file to pass through the modem).

I tried another test: Using `Tools - Start Play file from Radio` I configured freedv-gui to start playing the 700C demo file, before pressing Start.  This made the modem quickly transition out of acquisition and start decoding the file.  In this case pressing Stop stopped the program, i.e. expected behavior.  I think this worked as the CPU was < 100%.

Couple of ideas:
1. Most of the CPU is being consumed by freedv-gui - the core FreeDV API modem/codec is using < 10%, based on our command line tests. It would be interesting to profile freedv-gui.
2. In 700C the GUI somehow has to work a bit harder.  700C does have a shorter frame size, so maybe the CPU-hungry bottleneck is being called more often.
1. When run in non-real time, something breaks in either the FreeDV API (codec2 library) or freedv-gui. 

@UgoPoddine - do you have a Pi 4 available to try?

**Comment by tmiw** [comment] 2021-05-14 08:17
On that note, maybe it's time to revisit the idea of allowing users to disable the center panel? For instance, the main thread/drawing ops use a significant amount of CPU on macOS at least (and I wouldn't be surprised if that's the case elsewhere too):

<img width="1396" alt="Screen Shot 2021-05-14 at 1 14 21 AM" src="https://user-images.githubusercontent.com/449242/118242196-eb6be700-b451-11eb-9652-14020520e036.png">

Weirdly, other apps that use waterfall views (like piHPSDR) aren't nearly so greedy with CPU, so I'm not sure what's going on offhand.

**Comment by UgoPoddine** [comment] 2021-05-14 17:00
Hello Salem, David,

first of all thank-you very much for your help, really appreciated. 
Some remarks :

1) I can find a PI4 (that my 80years old mothers use for going in Internet :-)  ) but it will take a bit. I will try next week.
2) If I understand correctly the David's test, the issue, due to big CPU use, happens only if FreeDV "listen" to the frequency without finding a signal. If it starts deconding, the CPU use decreases and I can "stop" 700C.
3) In the past I had already noticed the apparently abnormal CPU use of 700C (I sent to David last year in June the pidstat files, if I remember correctly) : in the past this issue was so strong that crashed the GUI and forced me to build a small "no waterfall" wrapper around freedv_rx / freedv_tx (after David's suggestion), that I'm still using. Noi the GUI is surely more stable, on PI.
4) My general feeling is that the waterfall is not the real issue : with 700D it runs quite well, and - especially working with all analogue radios - it's useful for tuning the signal. On other "small bandwidth" DSP tools (e.g Freedv or WSJTX) having waterfall active doesn't affect performances. A bit worst is with CubicSDR (but it runs in any case on the PI3).
5) not well understood this topic : "When run in non-real time, something breaks in either the FreeDV API (codec2 library) or freedv-gui." : my tests were made in "real time", with FreeDV listening to the radio and with two dongle soundcards

Best regards
Ugo

**Comment by drowe67** [comment] 2021-05-15 03:31
@tmiw I agree - perhaps we can profile this on a non-Pi platform to find out where the CPU is going.  

@UgoPoddine as you say other SDR/GUI apps run fine, so it's probably just a chunk of inefficient code we need to find and refactor.

Lets see if we can identify that high CPU chunk of code, then decide on the best way forward.  From my command line test above I don't think it's the core 700C code in libcodec2, but it could be some sort of interaction between the libcodec2 and freedv-gui.

Another possibility is cache thrashing - the combination of the modem code and GUI running at the same time might cause the Pi to choke, e.g. if 700C uses more stack for it's DSP than say 700D.

**Comment by drowe67** [comment] 2021-05-15 04:19
I commented out the call to [freedv_comprx()](https://github.com/drowe67/freedv-gui/blob/master/src/freedv_interface.cpp#L498), which means we can't calling the demodulator DSP code at all, just running the sound card, resampling, and GUI code. On a Pi 3B I get:

| Center Panel | CPU Load % |
| --- | --- |
| scatter | 63 |
| from radio | 91 |
| waterfall | 79 |
| spectrum | 61 |

So it's pretty heavy in just the peripheral code, the 700C acquisition CPU load is probably just pushing it over the edge.  @timw as it was out of sync the scatter option above means no GUI Updates, and still a high CPU load.

Hmm, `codec2` is being built with `-O2` and freedv-gui with no optimisation flag.  I changed to `-O2` on freedv-gui but it didn't help much.  That suggests it's not the freedv-gui code, but perhaps some other layer, e.g. sound cards, resampling, or other library code.

**Comment by tmiw** [comment] 2021-05-15 04:57
@drowe67, I actually profiled freedv-gui earlier and I was seeing a lot of usage in PlotWaterfall. I've been tweaking it on and off all day and I was able to get CPU usage down by ~15-20 percentage points. I'll keep working on the other ones and report back.

**Comment by UgoPoddine** [comment] 2021-05-15 07:36
Hello mates,

you are too fast : difficult to follow...
From my side:

a) I'm using freedv_rx / freedvtx with an home made "no gui" wrapper (suggested by David) since several years on the PI3. In this scenario 700C runs smoothly (it's the best mode, at the moment, not extensively used 700E). Also the CPU consumption, still being higher than other modes, is accettable.
b) I made a remote test on the PI4, as suggested. The test is not in the same "real world" conditions because I have no USB dongle there and I was forced to use the internal PI4 soundcard + alsa loopback. In this scenario the waterfall is black, having nothing to listen. In any case, in this scenario, no issue in stopping 700C. A most realistic test requires time, being the PI4 far from my home.  

Thank-you for your efforts
73
Ugo

**Comment by tmiw** [comment] 2021-05-15 07:43
@UgoPoddine, mind trying the https://github.com/drowe67/freedv-gui/tree/ms-optimization branch? I was able to make significant performance improvements in all but the From Radio tab (but fortunately, CPU only seems to be used by a tab if it's actually displaying).

**Comment by UgoPoddine** [comment] 2021-05-15 10:25
Hello,

cloned and compiled b559954, but the issue is still there.

Thank-you for your effort.
Ugo

**Comment by drowe67** [comment] 2021-05-15 11:37
I've managed to make the modem 30% faster during acquisition in https://github.com/drowe67/codec2/pull/185

@UgoPoddine e cucinare cortaletta e arancini :grin: 

![anancini](https://user-images.githubusercontent.com/45574645/118359135-29d3e400-b5c1-11eb-895a-36658d8204ac.jpg)

**Comment by drowe67** [comment] 2021-05-15 12:10
OK using https://github.com/drowe67/codec2/pull/185 and building as a Release:
```
cd ~/freedv-gui/codec2/build_linux
git checkout dr-opt-cohpsk
cmake -DCMAKE_BUILD_TYPE=Release -DLPCNET_BUILD_DIR=~/LPCNet/build_linux ..
make
cd ~/~/freedv-gui/build_linux
make
```
freedv-gui b55995406 in 700C mode runs at about 100% CPU (with no valid signals, Waterfall panel, build freedv-gui with `-O2`), and **Stop** works.  I haven't tested it on any real signals yet, it's probably still borderline.

**Comment by UgoPoddine** [comment] 2021-05-15 12:30
Buon appetito, David.
Congratulation : no cucumbers on pizza like the ones seen in Melbourne some years ago and cotoletta seems perfect and very good  :-)
In the meantime I will build _e8aea2a_ from master : let me know if you need some other test.

Thank-you
Ugo

**Comment by tmiw** [comment] 2021-05-15 19:21
@drowe67, @UgoPoddine, can you try https://github.com/drowe67/freedv-gui/commit/949217f6021a67cd8de2a42365f0fb3ad8a11569? I was able to make improvements to the "From Radio" view but I'm also not sure it'll show any improvement on your end given that CPU isn't actually used by the tab in question unless you're viewing it.

**Comment by drowe67** [comment] 2021-05-15 20:58
@tmiw OK so I'm seeing:

| Center Panel | CPU Load % |
| --- | --- |
| scatter | 119 |
| from radio | 115 |
| waterfall | 99 |
| spectrum | 118 |

Stop/Stop is fine on 700C.

From Radio and To Spkr/Headphones does look  "glitchy" compared to before, at least on the Pi.  Scatter also seems to have very few points, and an unchanging central point at (0,0) at least on the Pi.

In general, lets carefully check the impact of the plot optimisation on x86 plattorms.  Operation on a Pi 3B is very much a corner case rather than a "must have" so we don't want to compromise the appearance and usability for 99.5% of the users.  Changes that speed up performance but don't affect appearance are fine.

One other issue - when I click on the "Timing Tab" I get a seg fault.

**Comment by drowe67** [comment] 2021-05-15 21:15
@timw, using freedv-gui/master e8aea2aed5e (as above out of sync ie acquisition)

| Center Panel | CPU Load % |
| --- | --- |
| scatter | 128 |
| from radio | 115 |
| waterfall | 102 |
| spectrum | 122 |

From Radio, To Spkr, Scatter, time look just like x86, and work fine.

Start/Stop works fine on 700C. but I haven't tried it with real off air signals.

**Comment by UgoPoddine** [comment] 2021-05-16 06:34
Thank-you, mates.

Just cloning 0a6d5e6 from ms-optimization.
I will let you know...

U

**Comment by UgoPoddine** [comment] 2021-05-16 07:38
Hello David,

freedv-gui git hash: 0a6d5e6
codec2 git hash: 306e4242

installed and tested.
The issue on 700C is still there, but the waterfall seems to run faster and smoother.

Ciao
Ugo

**Comment by tmiw** [comment] 2021-05-16 18:16
@UgoPoddine, https://github.com/drowe67/codec2/commit/341fb3f2bf1afd674e5445278a08bdeb85dd7a03 is the latest and includes some 700C optimizations. Can you try that one and see if the issue is diminshed?

**Comment by UgoPoddine** [comment] 2021-05-16 19:27
Hi Salem,  

not sure to have well done : I'm getting and compiling the last ms-optimization (as I can see that David updated it 3 hours ago).
Is your 341fb3f merged into it ?
If it's ok, I will let you know as soon the compilation ends.

thank-you
Ugo

**Comment by tmiw** [comment] 2021-05-16 19:32
> Hi Salem,
> 
> not sure to have well done : I'm getting and compiling the last ms-optimization (as I can see that David updated it 3 hours ago).
> Is your 341fb3f merged into it ?
> If it's ok, I will let you know as soon the compilation ends.
> 
> thank-you
> Ugo

Yeah, the build_linux.sh should automatically pull codec2 master so you'll likely have that one. You can verify by changing into the codec2 folder and running git log though.

**Comment by UgoPoddine** [comment] 2021-05-16 20:04
Hello mates,

you are really super....
With :
freedv-gui git hash: 6adad9f
codec2 git hash: 341fb3f2

The issue is solved and I can "stop" also 700C from the GUI.
I will test in a QSO tomorrow evening, if possible.
Really fantastic !
Thank-you for your effort, really appreciated.

Ugo

**Comment by UgoPoddine** [comment] 2021-05-18 14:39
Thank-you, mates

**Comment by UgoPoddine** [comment] 2021-12-27 17:46
Hello mates,

sorry for opening again this same issue.
Unfortunately the same problem is again happening on the same RaspberryPI 3+, exactly in the same conditions (that is : 700C only, strong CPU workload after having switched off 700C and only with 700C, and so on).
I'm now at FreeDV-GUI 737418b and PI/OS 5.10.63-v7+ #1496 (bullseye), 32 bits.
I'm not sure if the problem happened after the upgrade to bullseye or after some upgrade of the FreeDV version (it's a bit that I'm not using 700C).
If you need, pidstat trace available.

Sorry for the bad news, but in any case your work is still strongly appreciated.

Happy New Year
My best 73s
IU1IPB Ugo

**Comment by UgoPoddine** [comment] 2021-12-27 20:06
Hello, 

thank-you for the super fast answers...
The mine are :

a) of course 700C is not a "must", but I found it to be the best, according to audio quality, at least for mid-short distance QSOs (2000 Km). We use it frequently, indeed.
b) what is really strange is the situation already solved in May : the issue happens mainly trying to switch off the modem, not when it try to synchronize (at least : it's my impression). Before switching, it runs.
c) I'm not use overclocking : for PI3 it's not really recommended. In any case, for a small test, I can try to do.

thank-you 
Ugo





Are you using mode 700C for communications with other stations? Is this mode a must have?

The reason I ask, is the acquisition process is quite intensive when the modem is out of sync. It processes 6 times more symbols in order to search left and right for sync.

Are you using Turbo mode on your Pi? Maybe overclocking might help.

**Comment by tmiw** [comment] 2021-12-27 22:45
@srsampson posted the following in #149 so I'm including it here for reference:

> Are you using mode 700C for communications with other stations? Is this mode a must have?
>
> The reason I ask, is the acquisition process is quite intensive when the modem is out of sync. It processes 6 times more symbols in order to search left and right for sync.
>
> Are you using Turbo mode on your Pi? Maybe overclocking might help.

**Comment by tmiw** [comment] 2021-12-27 22:47
> Hello mates,
> 
> sorry for opening again this same issue. Unfortunately the same problem is again happening on the same RaspberryPI 3+, exactly in the same conditions (that is : 700C only, strong CPU workload after having switched off 700C and only with 700C, and so on). I'm now at FreeDV-GUI [737418b](https://github.com/drowe67/freedv-gui/commit/737418b51044d1ce5d5888d61ddc0b8c1dd167dd) and PI/OS 5.10.63-v7+ #1496 (bullseye), 32 bits. I'm not sure if the problem happened after the upgrade to bullseye or after some upgrade of the FreeDV version (it's a bit that I'm not using 700C). If you need, pidstat trace available.
> 
> Sorry for the bad news, but in any case your work is still strongly appreciated.
> 
> Happy New Year My best 73s IU1IPB Ugo

Here's a thought -- perhaps installing 64 bit Raspberry Pi OS will help? The compiler will probably be able to use Neon and other 64-bit optimizations and improve performance a bit.

**Comment by drowe67** [comment] 2021-12-28 00:01
@UgoPoddine - if you revert to the configuration you had in May, does the problem go away?

**Comment by UgoPoddine** [comment] 2021-12-31 08:28
Hello David, 

not sure to be able to do... sorry.
For reverting the GUI to  6adad9f correctly running on May, 16th, is it correct to use :

git checkout 6adad9f

?

Must I also downgrade the codec2 ?

Thank-you
Ugo

**Comment by tmiw** [comment] 2022-01-02 20:44
> Hello David,
> 
> not sure to be able to do... sorry. For reverting the GUI to [6adad9f](https://github.com/drowe67/freedv-gui/commit/6adad9f59bb83b7fe5b1a1c88f949a529252eed7) correctly running on May, 16th, is it correct to use :
> 
> git checkout [6adad9f](https://github.com/drowe67/freedv-gui/commit/6adad9f59bb83b7fe5b1a1c88f949a529252eed7)
> 
> ?
> 
> Must I also downgrade the codec2 ?
> 
> Thank-you Ugo

Yep, that's correct. While I don't recall any breaking API changes, I'd also recommend downgrading codec2 just to ensure that the configuration is fully equivalent to the working May one.

**Comment by UgoPoddine** [comment] 2022-01-14 17:49
Hello tmiw,

for avoiding errors, may I ask for your help in order to correctly download FreeDV and codec2 versions on 16/5/21 (FreeDV was  6adad9f ) ?

Thank-you
Ugo

**Comment by tmiw** [comment] 2022-01-15 19:14
> Hello tmiw,
> 
> for avoiding errors, may I ask for your help in order to correctly download FreeDV and codec2 versions on 16/5/21 (FreeDV was [6adad9f](https://github.com/drowe67/freedv-gui/commit/6adad9f59bb83b7fe5b1a1c88f949a529252eed7) ) ?
> 
> Thank-you Ugo

You should be able to edit the CODEC2_BRANCH line in build_linux.sh to something like the following for the correct version of codec2:

```
CODEC2_BRANCH=341fb3f2bf1afd674e5445278a08bdeb85dd7a03
```

And then do the following inside freedv-gui:

```
$ git checkout 6adad9f
$ ./build_linux.sh
```

Let me know if you require further assistance. 👍

**Comment by tmiw** [comment] 2022-02-20 22:29
@UgoPoddine, were you able to build using the instructions above?

**Comment by tmiw** [comment] 2022-04-03 19:39
I'm going to close this for now due to lack of recent updates. Feel free to reopen if this is still a problem.

**Closed by tmiw** 2022-04-03 19:39 UTC

**Comment by UgoPoddine** [comment] 2022-05-24 12:02
Hello Moneer,

last release has totally solved the issue on PI3, both on 32bit and on 64bit image, also allowing the whole decoding mode.

Thank-you very much to you and David for your effort, still hoping to be able to speak to you on radio
Ciao
Ugo

**Comment by drowe67** [comment] 2022-05-24 20:56
Well done Mooneer @tmiw :+1: !
