### ISSUE TITLE
[Software Issue] 

### ISSUE THREAD

**Issue by lw3dtr** [drowe67/freedv-gui#765] opened 2024-10-27 20:58 UTC
### Platform

Linux

### Platform Version

Linuxmint 21.3

### FreeDV Version

freedv-gui-2.0.0-20241018

### Steps to Reproduce

I just compile perfectly source on linux , when i select RADE and pick on start button and the program exits whit this error

bruno@bruno-ThinkPad-L15-Gen-2:~/Descargas/freedv-gui-2.0.0-20241018$ ./build_linux/src/freedv
Using RADE API version 1

(freedv:4398): Gtk-WARNING **: 17:55:05.363: Negative content width -17 (allocation 9, extents 13x13) while allocating gadget (node button, owner GtkButton)

(freedv:4398): Gtk-WARNING **: 17:55:05.369: Negative content width -17 (allocation 9, extents 13x13) while allocating gadget (node button, owner GtkButton)
[2024-10-27 17:55:07] [connect] Successful connection
[2024-10-27 17:55:07] [connect] WebSocket Connection 208.85.243.198:80 v-2 "WebSocket++/0.8.2" /socket.io/?EIO=4&transport=websocket&t=1730062505 101
model file: TBD
import_array returned: 0
ModuleNotFoundError: No module named 'radae_txe'
Error: importing radae_txe

### Expected Behavior

I do not know if it is my problem or what

### Actual Behavior

![Captura de pantalla de 2024-10-27 17-57-17](https://github.com/user-attachments/assets/6ea56129-1a2e-4ad2-8450-c45f9be3d99a)
![Captura de pantalla de 2024-10-27 17-57-09](https://github.com/user-attachments/assets/2eeff89c-a4f1-4808-a486-741dfe6acba6)

### Additional Comments

I am new to freedv  , may be it is a problem on my pc

**Comment by tmiw** [comment] 2024-10-28 01:19
This is a duplicate of https://github.com/drowe67/freedv-gui/issues/749. Please see [the latest README](https://github.com/drowe67/freedv-gui/blob/v2.0-dev/README.md#running-rade-mode-on-linux), which contains general instructions for running on Linux.

**Closed by tmiw** 2024-10-28 01:19 UTC
Labels: bug
