### ISSUE TITLE
FreeDV randomly will switch the radio between USB & LSB mode

### ISSUE THREAD

**Issue by Kimberly-McBlaze** [drowe67/freedv-gui#431] opened 2023-06-11 08:44 UTC
This happened on versions 1.8.10.1 and below. When I'm on 20m and above and using USB mode, FreeDV will, at random, switch the radio to LSB mode. A similar thing happens on 40m and below when I'm on LSB mode, it would at random switch the radio to USB mode. Sometimes, I can switch the radio manually back to the appropriate mode, but after a while, FreeDV will switch the radio to the opposite mode. On rare occasions, when I try to manually switch modes, FreeDV would somehow keep the mode locked in by instantly switching the radio back. The radio is uBitx v6, which emulates the FT-817 for cat controls.

**Comment by Tyrbiter** [comment] 2023-06-11 10:44
@tmiw Worth a test build with hamlib-4.6~git, the recent FT-817 CAT changes are not in hamlib-4.5.5

I'm not sure how closely the uBitx v6 emulation is to the Yaesu version.

**Comment by Kimberly-McBlaze** [comment] 2023-06-11 11:27
> 

Well, it does respond to pretty much all of the FT-817 commands, so I guess the uBitx does a good job at emulating the 817.

**Comment by Tyrbiter** [comment] 2023-06-11 11:59
> @Tyrbiter Well, it does respond to pretty much all of the FT-817 commands, so I guess the uBitx does a good job at emulating the 817.

Which is good, but @tmiw recently diagnosed and fixed some erroneous behaviour in the development hamlib version regarding mode switching problems with the FT-817, this could also be the cause of strange behaviour with your uBitx v6.

**Comment by tmiw** [comment] 2023-06-11 17:56
Note: @Kimberly-McBlaze is using Windows 11 per another reported issue.

> Which is good, but @tmiw recently diagnosed and fixed some erroneous behaviour in the development hamlib version regarding mode switching problems with the FT-817, this could also be the cause of strange behaviour with your uBitx v6.

Though a significant part of those changes were actually updating the EEPROM on the 817. I don't know if that would particularly impact uBitx, but then again, the 817 CAT protocol also doesn't have specific DIGU and DIGL modes (just "DIG" + updating Menu 26).

However, the most recent versions did bring back dynamic linking for hamlib, so in theory you should be able to replace libhamlib-4.dll in C:\\Program Files\\FreeDV\\... with one from another version of hamlib. Would it help if I compiled a version of that DLL from the latest hamlib code and dropped it here for you to try?

**Comment by Tyrbiter** [comment] 2023-06-11 18:49
The daily builds of libhamlib-4.dll can be found on Sourceforge here:

https://n0nb.users.sourceforge.net/

the file you want is this one

https://n0nb.users.sourceforge.net/dll64/libhamlib-4.dll

it's sensible to keep the one you have as occasionally this daily dll gets broken if a hamlib master change is problematic.

**Comment by Kimberly-McBlaze** [comment] 2023-06-11 22:12
@Tyrbiter 

so far, so good... I tried that version of libhamlib and it seems to be running okay. FreeDV also seems to start much faster with this DLL too. I will continue testing and monitoring this to make sure it really is going to work and I'll report my findings when I'm done testing. One interesting behavior is that it likes to default to LSB mode no matter what band I select, but we'll see if it stays on USB mode after manually switching it on the radio.

**Comment by Kimberly-McBlaze** [comment] 2023-06-12 01:59
ok, so after quite a bit of testing, this is what I found:

With this new DLL in place, things seem to be mostly stable, it again starts much faster, and generally works better, though there are still a few issues.


The random switch between USB/LSB still happens, but not as often, it seems to be a rare occurrence now.


Occasionally, hamlib will spit out a PTT error, but somehow, it keeps working anyway, though it would display the error message every time I stop PTT and it also no longer receives frequency info from the radio when I move the VFO when this error happens. On some occasions, this error would also cause FreeDV to crash. This error is corrected when I restart FreeDV.


Switching between analog and digital would cause the switch from USB to LSB, the same thing happens when simply pressing the "start" button.

**Comment by tmiw** [comment] 2023-06-12 08:52
I'm not sure this will help with the USB/LSB switching issue but you can try this build from the latest in #429: 
[FreeDV-1.8.10.1-windows-x86_64.exe.zip](https://github.com/drowe67/freedv-gui/files/11720314/FreeDV-1.8.10.1-windows-x86_64.exe.zip). You'll need to replace libhamlib-4.dll with the nightly build as previously done, though.

Also, to hopefully rule out anything on the rig control side contributing to your occasional crashes, that version should have an option in Tools->Options->Rig Control to restore pre-1.8.10 behavior (where only PTT is controlled). Enabling that and running it that way for a while should hopefully tell us if it's the recent hamlib changes or some combination of the previous hamlib logic/its integration with FreeDV as a whole.

**Comment by Kimberly-McBlaze** [comment] 2023-06-12 11:46
that version is identical to the one that was sent to me via my other thread, but I went ahead and uninstalled the other one and installed this one and copied over the new hamlib dll and now everything is very broken. I uninstalled this and reinstalled the one I got yesterday, as well as re-copy the new hamlib dll, and it's still very broken. The program is much slower to start, if it does start at all, but almost always stops responding and crash. The program is totally and completely unusable, unless I disable hamlib altogether and forgo any cat controls. Just as a test, I restored the included hamlib and that didn't fix anything.

The radio itself has no problems at all, I can use other programs, like FT8, JS8, FLDIGI, Winlink, VarAC, and others just fine without any problem at all and the radio never experiences any weird behavior on those problems, it's only with FreeDV do weird things happen.

**Comment by Tyrbiter** [comment] 2023-06-12 16:38
Could the freedv settings file in your home directory have become corrupted? I'm thinking it would be sensible to find it and delete it.

@tmiw will know if it has a different name on Windows.

**Comment by tmiw** [comment] 2023-06-12 17:48
> Could the freedv settings file in your home directory have become corrupted? I'm thinking it would be sensible to find it and delete it.
> 
> @tmiw will know if it has a different name on Windows.

On Windows, settings are stored in the Registry by default (HKEY_CURRENT_USER\SOFTWARE\CODEC2-Project\FreeDV). Unfortunately, I don't think this is it; it sounds like adding the check for VFO_SUB might have broken support on the uBitx somehow. 

As mentioned in the other issue, hamlib issues shouldn't be taking out FreeDV altogether, so I'll work on making that less likely.

**Comment by Kimberly-McBlaze** [comment] 2023-06-12 21:17
Ok, so deleting the entire "HKEY_CURRENT_USER\Software\freedv" registry made the program work again.

**Comment by Tyrbiter** [comment] 2023-06-12 22:46
> Ok, so deleting the entire "HKEY_CURRENT_USER\Software\freedv" registry made the program work again.
> 
> @Tyrbiter was correct about the settings being corrupt, it seems like installing and running different builds of the program cause the settings to become corrupted.

That's a bit weird but maybe @tmiw can think of a mechanism for that, I have to say that I have not seen this happen with freedv on Linux but there is no registry so the code that stores the settings is different.

I think we're all hoping that the difficulties that caused all the various patch versions have been understood now and there is now a path to a new release with everyone happy.

**Comment by tmiw** [comment] 2023-06-13 01:51
Not sure why clearing the Registry would fix things, but glad everything's good now. I'll close this bug for now; feel free to reopen if the issue comes back.

**Closed by tmiw** 2023-06-13 01:51 UTC
