### ISSUE TITLE
Error in compiling FreeDV on ARM64 on Raspberry PI

### ISSUE THREAD

**Issue by UgoPoddine** [drowe67/freedv-gui#149] opened 2021-07-15 12:15 UTC
Hi everyone,

I'm trying to build, using the usual script build_linux.sh, FreeDV-GUI over an ARM64 image on RaspberryPI3+
FreeDV GUI last commit (937e8be).
Linux 5.10.17-v8+ #1421 SMP PREEMPT Thu May 27 14:01:37 BST 2021 aarch64 GNU/Linux
The building process abends as follow.

Can you help ? thank-you very much
Best regards
Ugo

[...]

[  3%] Building CXX object src/CMakeFiles/freedv.dir/dlg_audiooptions.cpp.o
cd /home/pi/FreeDV/freedv-gui/build_linux/src && /usr/bin/c++  -DGIT_HASH=\"937e8be\" -DWXUSINGDLL -D_FILE_OFFSET_BITS=64 -D__WXGTK__ -I/home/pi/FreeDV/freedv-gui/src -I/home/pi/FreeDV/freedv-gui/build_linux/src -I/home/pi/FreeDV/freedv-gui/build_linux -isystem /usr/lib/arm-linux-gnueabihf/wx/include/gtk2-unicode-3.0 -isystem /usr/include/wx-3.0 -isystem /home/pi/FreeDV/freedv-gui/codec2/src -isystem /home/pi/FreeDV/freedv-gui/codec2/build_linux -isystem /home/pi/FreeDV/freedv-gui/LPCNet/src  -Wall -pthread -g   -o CMakeFiles/freedv.dir/dlg_audiooptions.cpp.o -c /home/pi/FreeDV/freedv-gui/src/dlg_audiooptions.cpp
In file included from /home/pi/FreeDV/freedv-gui/src/main.h:33,
                 from /home/pi/FreeDV/freedv-gui/src/dlg_audiooptions.cpp:22:
/usr/include/wx-3.0/wx/filename.h: In static member function \u2018static wxUniChar wxFileName::GetPathSeparator(wxPathFormat)\u2019:
/usr/include/wx-3.0/wx/filename.h:473:43: error: ambiguous overload for \u2018operator[]\u2019 (operand types are \u2018wxString\u2019 and \u2018unsigned int\u2019)
         { return GetPathSeparators(format)[0u]; }
                                           ^
/usr/include/wx-3.0/wx/filename.h:473:43: note: candidate: \u2018operator[](const wchar_t*, long int)\u2019 <built-in>
/usr/include/wx-3.0/wx/filename.h:473:43: note: candidate: \u2018operator[](const char*, long int)\u2019 <built-in>
In file included from /usr/include/wx-3.0/wx/memory.h:15,
                 from /usr/include/wx-3.0/wx/object.h:19,
                 from /usr/include/wx-3.0/wx/wx.h:15,
                 from /home/pi/FreeDV/freedv-gui/src/main.h:27,
                 from /home/pi/FreeDV/freedv-gui/src/dlg_audiooptions.cpp:22:
/usr/include/wx-3.0/wx/string.h:1544:15: note: candidate: \u2018wxUniChar wxString::operator[](int) const\u2019
     wxUniChar operator[](int n) const
               ^~~~~~~~
/usr/include/wx-3.0/wx/string.h:1546:15: note: candidate: \u2018wxUniChar wxString::operator[](long int) const\u2019
     wxUniChar operator[](long n) const
               ^~~~~~~~
/usr/include/wx-3.0/wx/string.h:1548:15: note: candidate: \u2018wxUniChar wxString::operator[](size_t) const\u2019
     wxUniChar operator[](size_t n) const
               ^~~~~~~~
/usr/include/wx-3.0/wx/string.h:1556:18: note: candidate: \u2018wxUniCharRef wxString::operator[](int)\u2019
     wxUniCharRef operator[](int n)
                  ^~~~~~~~
/usr/include/wx-3.0/wx/string.h:1558:18: note: candidate: \u2018wxUniCharRef wxString::operator[](long int)\u2019
     wxUniCharRef operator[](long n)
                  ^~~~~~~~
/usr/include/wx-3.0/wx/string.h:1560:18: note: candidate: \u2018wxUniCharRef wxString::operator[](size_t)\u2019
     wxUniCharRef operator[](size_t n)
                  ^~~~~~~~
make[2]: *** [src/CMakeFiles/freedv.dir/build.make:63: src/CMakeFiles/freedv.dir/dlg_audiooptions.cpp.o] Error 1
make[2]: Leaving directory '/home/pi/FreeDV/freedv-gui/build_linux'
make[1]: *** [CMakeFiles/Makefile2:115: src/CMakeFiles/freedv.dir/all] Error 2
make[1]: Leaving directory '/home/pi/FreeDV/freedv-gui/build_linux'
make: *** [Makefile:152: all] Error 2

**Comment by srsampson** [comment] 2021-07-15 14:10
Here's something from a few years ago:

http://yasriady.blogspot.com/2015/10/how-to-build-wxwidgets-for-raspberry-pi.html

**Comment by UgoPoddine** [comment] 2021-07-15 15:09
Hello Srsampson ,

Thank-you for your suggestion.
Not sure this is really related ... we can compile FreeDV on RaspberryPI3 with build_linux.sh since several years, without any issue, at least with 32bit OS images. My raspberry PI work now very well also withe the FreeDV GUI, after optimizations made by David & friend two months ago.
The reported issue happens if I try to compile on the same machine when using the (almost) new 64bit OS Image.
Consider that all requested dependencies, including WXWidgets, are installed on the machine from Debian ARM64 repository, without any issue.

Best regards
73, Ugo

**Comment by tmiw** [comment] 2021-07-15 16:13
This looks like an issue with the wxWidgets version included with Debian ARM64. Can you try to build freedv-gui by doing the following?

```
cd build_linux
rm -rf *
cmake  -DCMAKE_BUILD_TYPE=Debug  -DBOOTSTRAP_WXWIDGETS=1 -DCODEC2_BUILD_DIR=/home/user/freedv-gui/codec2/build_osx -DLPCNET_BUILD_DIR=/home/user/freedv-gui/LPCNet/build_osx ..
make VERBOSE=1

cmake  -DCMAKE_BUILD_TYPE=Debug  -DBOOTSTRAP_WXWIDGETS=1 -DCODEC2_BUILD_DIR=/home/user/freedv-gui/codec2/build_osx -DLPCNET_BUILD_DIR=/home/user/freedv-gui/LPCNet/build_osx ..
make VERBOSE=1
```

(Yes, you're running the exact same cmake and make commands twice. This is currently required if you're having freedv-gui build wxWidgets for you.)

**Comment by tmiw** [comment] 2021-07-19 04:19
FWIW I just tried using both an ARM64 Ubuntu 20.04 and a Debian 10.10 VM on an M1 Mac to compile FreeDV (commit https://github.com/drowe67/freedv-gui/commit/937e8bea7e143e1e9c620fbe7933aeea74ede784) and had no issues. Screenshot from Ubuntu:

![Screen Shot 2021-07-18 at 9 01 14 PM](https://user-images.githubusercontent.com/449242/126101356-31b4b4fb-121a-466c-b756-11319606b0a7.png)

It's possible that they fixed the wxWidgets packages in the last few days, so perhaps run apt update && apt upgrade, remove the LPCNet/codec2/build_linux folders and try running build_linux.sh again?

**Comment by UgoPoddine** [comment] 2021-07-19 18:18
thank-you Salem.
I will try to upgrade and to newly compile tomorrow evening and I will let you know.

Ugo

Il giorno 19 lug 2021, 06:19, alle ore 06:19, Mooneer Salem ***@***.***> ha scritto:

**Comment by UgoPoddine** [comment] 2021-07-20 16:16
Thank-you Salem.

I have verified : 

a) the up-to-date status of the 64bit image (and it was ok) : 

Linux 5.10.17-v8+ #1421 SMP PREEMPT 

b) the dependencies situation (as in the FreeDV documentation and as you have kindly listed) : and it was ok
c) the version of wxwidgets with python -c "import wx;print wx.__version__" : the version is 3.0.2.0 both on the 32 bit machine and on the 64bit image.

Unfortunately, the building process (with the build_linux script) still aborts in the same statement, as below.
Must I try to compile differently ?

Thank-you
Ugo
 

n file included from /home/pi/FreeDV/freedv-gui/src/main.h:33,
                 from /home/pi/FreeDV/freedv-gui/src/dlg_audiooptions.cpp:22:
/usr/include/wx-3.0/wx/filename.h: In static member function \u2018static wxUniChar wxFileName::GetPathSeparator(wxPathFormat)\u2019:
/usr/include/wx-3.0/wx/filename.h:473:43: **error: ambiguous overload** for \u2018operator[]\u2019 (operand types are \u2018wxString\u2019 and \u2018unsigned int\u2019)
         { return GetPathSeparators(format)[0u]; }
                                           ^
/usr/include/wx-3.0/wx/filename.h:473:43: note: candidate: \u2018operator[](const wchar_t*, long int)\u2019 <built-in>
/usr/include/wx-3.0/wx/filename.h:473:43: note: candidate: \u2018operator[](const char*, long int)\u2019 <built-in>
In file included from /usr/include/wx-3.0/wx/memory.h:15,
                 from /usr/include/wx-3.0/wx/object.h:19,
                 from /usr/include/wx-3.0/wx/wx.h:15,
                 from /home/pi/FreeDV/freedv-gui/src/main.h:27,
                 from /home/pi/FreeDV/freedv-gui/src/dlg_audiooptions.cpp:22:
/usr/include/wx-3.0/wx/string.h:1544:15: note: candidate: \u2018wxUniChar wxString::operator[](int) const\u2019
     wxUniChar operator[](int n) const
               ^~~~~~~~
/usr/include/wx-3.0/wx/string.h:1546:15: note: candidate: \u2018wxUniChar wxString::operator[](long int) const\u2019
     wxUniChar operator[](long n) const
               ^~~~~~~~
/usr/include/wx-3.0/wx/string.h:1548:15: note: candidate: \u2018wxUniChar wxString::operator[](size_t) const\u2019
     wxUniChar operator[](size_t n) const
               ^~~~~~~~
/usr/include/wx-3.0/wx/string.h:1556:18: note: candidate: \u2018wxUniCharRef wxString::operator[](int)\u2019
     wxUniCharRef operator[](int n)
                  ^~~~~~~~
/usr/include/wx-3.0/wx/string.h:1558:18: note: candidate: \u2018wxUniCharRef wxString::operator[](long int)\u2019
     wxUniCharRef operator[](long n)
                  ^~~~~~~~
/usr/include/wx-3.0/wx/string.h:1560:18: note: candidate: \u2018wxUniCharRef wxString::operator[](size_t)\u2019
     wxUniCharRef operator[](size_t n)
                  ^~~~~~~~
make[2]: *** [src/CMakeFiles/freedv.dir/build.make:63: src/CMakeFiles/freedv.dir/dlg_audiooptions.cpp.o] Error 1
make[2]: Leaving directory '/home/pi/FreeDV/freedv-gui/build_linux'
make[1]: *** [CMakeFiles/Makefile2:115: src/CMakeFiles/freedv.dir/all] Error 2
make[1]: Leaving directory '/home/pi/FreeDV/freedv-gui/buil

**Comment by tmiw** [comment] 2021-07-21 01:48
@UgoPoddine, can you apply this patch and try again? This will force the build process to build a local copy of wxWidgets and should hopefully avoid the prebuilt version:

```
diff --git a/build_linux.sh b/build_linux.sh
index 8e26be4..cf072da 100755
--- a/build_linux.sh
+++ b/build_linux.sh
@@ -39,5 +39,7 @@ export LD_LIBRARY_PATH=$LPCNETDIR/build_linux/src
 # Finally, build freedv-gui
 cd $FREEDVGUIDIR && git pull
 mkdir  -p build_linux && cd build_linux && rm -Rf *
-cmake -DCMAKE_BUILD_TYPE=Debug -DCODEC2_BUILD_DIR=$CODEC2DIR/build_linux -DLPCNET_BUILD_DIR=$LPCNETDIR/build_linux ..
+cmake -DCMAKE_BUILD_TYPE=Debug -DBOOTSTRAP_WXWIDGETS=1 -DCODEC2_BUILD_DIR=$CODEC2DIR/build_linux -DLPCNET_BUILD_DIR=$LPCNETDIR/build_linux ..
+make VERBOSE=1
+cmake -DCMAKE_BUILD_TYPE=Debug -DBOOTSTRAP_WXWIDGETS=1 -DCODEC2_BUILD_DIR=$CODEC2DIR/build_linux -DLPCNET_BUILD_DIR=$LPCNETDIR/build_linux ..
 make VERBOSE=1
```

**Comment by tmiw** [comment] 2021-07-26 09:02
BTW I finally got around to installing a fresh copy of the 64 bit version of Raspberry Pi OS on my Pi 4B and I was able to compile without needing to use -DBOOTSTRAP_WXWIDGETS=1. Maybe the wxWidgets packages simply need to be reinstalled?

```
sudo apt remove libwxgtk3.0-gtk3-0v5 libwxgtk3.0-gtk3-dev
sudo apt install libwxgtk3.0-gtk3-0v5 libwxgtk3.0-gtk3-dev
```

**Comment by tmiw** [comment] 2021-08-13 07:46
@UgoPoddine, any updates on this?

**Comment by UgoPoddine** [comment] 2021-08-15 12:56
Hello Salem,

thank-you very mich for your help, really apprecaited.

Unfortunately I was a bit busy end of July and now I'm (sorry about that 
... :-) in holiday till first days of September.

Two weeks ago, after having made a general system update of the ARM64 
image, I have tried to compile again FreeDV (last version from GitHub), 
getting exactly the same error.

I have not yet tried to uninstall WXWidget yet as you suggested (I will 
do once at lab again), but consider that the ARM64 image that I'm using 
is clean and recent and not jammed.

I will perform all your suggested checks on my PI3 once at lab again : 
sorry for the anoyance.

I have the mood that some dependecy is missing, but not sure of course...


Thank-you

Ugo

**Comment by tmiw** [comment] 2021-11-10 09:01
@UgoPoddine, any update here?

**Comment by UgoPoddine** [comment] 2021-11-10 10:32
Hello Salem,

You are right...
Unfortunately my PI3 OS 64bit image was corrupted and I found no time to reinstall it.
I will do asap and I will give you an answer.
Sorry for the delay, thank-you for your valuable support.

Ugo

Il giorno 10 nov 2021, 10:01, alle ore 10:01, Mooneer Salem ***@***.***> ha scritto:
***@***.***, any update here?

**Comment by srsampson** [comment] 2021-12-27 18:57
Are you using mode 700C for communications with other stations? Is this mode a must have?

The reason I ask, is the acquisition process is quite intensive when the modem is out of sync. It processes 6 times more symbols in order to search left and right for sync.

Are you using Turbo mode on your Pi? Maybe overclocking might help.

**Comment by tmiw** [comment] 2021-12-27 22:43
> Are you using mode 700C for communications with other stations? Is this mode a must have?
> 
> The reason I ask, is the acquisition process is quite intensive when the modem is out of sync. It processes 6 times more symbols in order to search left and right for sync.
> 
> Are you using Turbo mode on your Pi? Maybe overclocking might help.

I think this is supposed to be a response to #126. I'll copy this post over there.

**Comment by tmiw** [comment] 2022-02-20 22:30
I'm going to close this because it looks like discussion has moved to #126. If that's not the case, please feel free to reopen. 👍

**Comment by UgoPoddine** [comment] 2022-04-29 15:07
Hello Salem,

after the evolution of the ARM64 PI OS version, I have finally tried again to compile FreeDV on RaspberryPI3+.
This time the building process was successful, and FreeDV was active on my machine.
Unfortunately, differently from the ssame version running on the same machine on 32bit Bullseye, the FreeDV-GUI gas some issue. 
It happens here on all modes (including 700D and 700E) what on the 32bit happens only on 700C (described in other issue).
I can start the reception, I can transmit, but, if i try to stop the mode (no reception, no transmsission), FreeDV-gui goes in a kind of neverending loop and the only way to stop is to kill the application.
On 32bit in can be acceptable because 700C is less used than in the past (still being my preferred for short range QSOs), but  now the other modes are not usable.
Please consider that, two years ago, the issue happened and you were able to solve, then it happened again some versions ahead.

Thank-you
Regards
Ugo

**Comment by tmiw** [comment] 2022-04-30 07:54
@UgoPoddine, I'm reopening this issue while we determine how exactly to reproduce below. If/when we do, we can make a new issue for it.

> after the evolution of the ARM64 PI OS version, I have finally tried again to compile FreeDV on RaspberryPI3+. This time the building process was successful, and FreeDV was active on my machine. Unfortunately, differently from the ssame version running on the same machine on 32bit Bullseye, the FreeDV-GUI gas some issue. It happens here on all modes (including 700D and 700E) what on the 32bit happens only on 700C (described in other issue). I can start the reception, I can transmit, but, if i try to stop the mode (no reception, no transmsission), FreeDV-gui goes in a kind of neverending loop and the only way to stop is to kill the application. On 32bit in can be acceptable because 700C is less used than in the past (still being my preferred for short range QSOs), but now the other modes are not usable. Please consider that, two years ago, the issue happened and you were able to solve, then it happened again some versions ahead.

I've been testing on a Raspberry Pi 4B with 4GB of RAM (with the latest [64 bit Raspberry Pi OS](https://www.raspberrypi.com/software/)) and I haven't been able to duplicate this so far. My setup:

**Radio**: Hermes Lite 2 using Quisk as the SDR software
* *Digital TX/RX sound cards*: PulseAudio managed QuiskDigitalInput and QuiskDigitalOutput devices.
* *CAT interface*: TCP/IP localhost port 4575

**FreeDV**: 1.8.0 (git branch `ms-2020-experiment`, hash `9bd9661`, built in PulseAudio mode with `./build_linux.sh pulseaudio`)
* *RX sound cards*: digital = `QuiskDigitalOutput.monitor`, analog = Pi HDMI device
* *TX sound cards*: digital = `QuiskDigitalInput`, analog = Pi 3.5mm jack (no available microphone at the moment)
* *PTT*: Hamlib NET rigctl at localhost:4575

I've tried the following combinations of settings in Tools->Options->Modem as well:

* "Simultaneously Decode All HF Modes" and "Use single thread for multiple RX operation" checked
* "Simultaneously Decode All HF Modes" checked and "Use single thread for multiple RX operation" unchecked
* "Simultaneously Decode All HF Modes" unchecked

free/cpuinfo output for reference:

```
mooneer@raspberrypi:~/freedv-gui/build_linux $ free
               total        used        free      shared  buff/cache   available
Mem:         3885552      329064     2319944       81136     1236544     3398132
Swap:         102396        1536      100860
mooneer@raspberrypi:~/freedv-gui/build_linux $ cat /proc/cpuinfo
processor       : 0
BogoMIPS        : 108.00
Features        : fp asimd evtstrm crc32 cpuid
CPU implementer : 0x41
CPU architecture: 8
CPU variant     : 0x0
CPU part        : 0xd08
CPU revision    : 3

processor       : 1
BogoMIPS        : 108.00
Features        : fp asimd evtstrm crc32 cpuid
CPU implementer : 0x41
CPU architecture: 8
CPU variant     : 0x0
CPU part        : 0xd08
CPU revision    : 3

processor       : 2
BogoMIPS        : 108.00
Features        : fp asimd evtstrm crc32 cpuid
CPU implementer : 0x41
CPU architecture: 8
CPU variant     : 0x0
CPU part        : 0xd08
CPU revision    : 3

processor       : 3
BogoMIPS        : 108.00
Features        : fp asimd evtstrm crc32 cpuid
CPU implementer : 0x41
CPU architecture: 8
CPU variant     : 0x0
CPU part        : 0xd08
CPU revision    : 3

Hardware        : BCM2835
Revision        : c03111
Serial          : 100000007a32407d
Model           : Raspberry Pi 4 Model B Rev 1.1
mooneer@raspberrypi:~/freedv-gui/build_linux $ uname -a
Linux raspberrypi 5.15.32-v8+ #1538 SMP PREEMPT Thu Mar 31 19:40:39 BST 2022 aarch64 GNU/Linux
mooneer@raspberrypi:~/freedv-gui/build_linux $ 
```

My suggested next steps:

* Let me know what radio and other settings you're using. I have a few physical radios I can try plugging into the Pi if that'll help.
* Try unchecking "Simultaneously Decode All HF Modes" in Tools->Options->Modem. On CPU limited systems, this can help if the cause is indeed resource starvation.
* Sync up to the Git branch that I tried and see if that makes a difference (`git checkout ms-2020-experiment && git pull && rm -rf build_linux codec2 LPCNet && ./build_linux.sh`). At the time of this writing, it shouldn't differ too much from master but it doesn't hurt for both of us to be using the same code.
* If you're using PortAudio, try using PulseAudio like I did above (add `pulseaudio` to the end of `build_linux.sh`, e.g. `./build_linux.sh pulseaudio`). The latter tends to work a *lot* better on Linux systems in general.

Anyway, let me know how it goes or if you have any questions.

**Comment by UgoPoddine** [comment] 2022-05-01 08:26
Hello Salem,

thank-you a usual.

preliminary short answers and one info more :

a) Hardware :

cat /proc/cpuinfo
processor       : 0
model name      : ARMv7 Processor rev 4 (v7l)
BogoMIPS        : 76.80
Features        : half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt                                                                                                              vfpd32 lpae evtstrm crc32
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x0
CPU part        : 0xd03
CPU revision    : 4

processor       : 1
model name      : ARMv7 Processor rev 4 (v7l)
BogoMIPS        : 76.80
Features        : half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt                                                                                                              vfpd32 lpae evtstrm crc32
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x0
CPU part        : 0xd03
CPU revision    : 4

processor       : 2
model name      : ARMv7 Processor rev 4 (v7l)
BogoMIPS        : 76.80
Features        : half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt                                                                                                              vfpd32 lpae evtstrm crc32
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x0
CPU part        : 0xd03
CPU revision    : 4

processor       : 3
model name      : ARMv7 Processor rev 4 (v7l)
BogoMIPS        : 76.80
Features        : half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt                                                                                                              vfpd32 lpae evtstrm crc32
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x0
CPU part        : 0xd03
CPU revision    : 4

Hardware        : BCM2835
Revision        : a02082
Serial          : 0000000062e7a86f
Model           : Raspberry Pi 3 Model B Rev 1.2

2) Memory (I wonder here the issue) when running 32bit OS image

free
               total        used        free      shared  buff/cache   available
Mem:          944980      261124      323760        9512      360096      620352
Swap:        1048572      208640      839932

3) Please, don't ask me to run PulseAudio if possible.... It gives huge issues on different other programs and i's quite heavvy for the PI.....

4) I will try to uncheck "Simultaneously Decode All HF Modes" once at home again tomorrow
5) I will install git checkout ms-2020-experiment once at home
6) Finally, regarding radio, my radio is an "old lady" born in 1979 (TS180S), without CAT. I simply ask applications to set the PTT on RS232 RTS (then piped on Gpio): 

The new information :

Yesterday I have installed the same image (same "physic" MicroSD :-)  ) on a RaspberryPI4 machine with this situation : 

free
               total        used        free      shared  buff/cache   available
Mem:         3930868      649504     2376344       87080      905020     3056712
Swap:         102396           0      102396

The FreeDV gui issue doesn't happen any more and I was able to start and stop also 700C without any issue. 

Thank-you again
Best regards
Ugo

**Comment by tmiw** [comment] 2022-05-01 22:26
> a) Hardware :
> 
> [snipped]
>
> Hardware : BCM2835 Revision : a02082 Serial : 0000000062e7a86f Model : Raspberry Pi 3 Model B Rev 1.2

Yeah that would most likely explain why I didn't see the issue. Unfortunately I don't have a Pi 3B here, just a few Pi 2s and the Pi 4 I previously tested on. I'll have to wait until the 3B goes back in stock somewhere before I can test further on the same hardware.

> 2. Memory (I wonder here the issue)

IIRC, FreeDV doesn't actually use that much RAM when it's running. While macOS isn't directly comparable to Linux, it only seems to use ~120MB of RAM on my Intel MacBook Pro while actively decoding 700E.

> 3. Please, don't ask me to run PulseAudio if possible.... It gives huge issues on different other programs and i's quite heavvy for the PI.....

If I can get a hold of a Pi 3B, I can try. I'm not sure yet if it matters for this specific issue but just to be sure.

> 4. I will try to uncheck "Simultaneously Decode All HF Modes" once at home again tomorrow
> 5. I will install git checkout ms-2020-experiment once at home

Let me know how these go!

> 6. Finally, regarding radio, my radio is an "old lady" born in 1979 (TS180S), without CAT. I simply ask applications to set the PTT on RS232 RTS (then piped on Gpio):

Another thing you can try is to disable PTT entirely. That might rule out anything related to handling of it.

**Comment by UgoPoddine** [comment] 2022-05-04 06:50
Hello Salem,

thank-you a usual.

some answers  :

1) Hardware : the concerned RaspberryPI3 is exposed on the Internet. Feel free, you need, to access it on SSH or VNC. Let me know, I will give you the address.
2) "uncheck "Simultaneously Decode All HF Modes" : this solves the issue for all modes excluding 700C (in this way, reverting to the 32bits image behaviour)
5) "experimental image installation" : not yet done, but very soon : sorry
6) "disable PTT entirely" : this has no effect

Thank-you
Best regards
Ugo

**Comment by tmiw** [comment] 2022-05-05 18:18
> 1. Hardware : the concerned RaspberryPI3 is exposed on the Internet. Feel free, you need, to access it on SSH or VNC. Let me know, I will give you the address.

If you can email me the information for this (mooneer@gmail.com), that would be appreciated. I can also send you my SSH key if that's preferred.

> 3. "experimental image installation" : not yet done, but very soon : sorry

No worries!

> 4. "disable PTT entirely" : this has no effect

Interesting, I'm not sure what could be causing that offhand. When I get onto the Pi I can take a closer look.

**Comment by tmiw** [comment] 2022-05-23 22:29
Going to close this issue due to #236 being merged. Feel free to open a new issue if you run into anything else.

**Closed by tmiw** 2022-05-23 22:29 UTC
