### ISSUE TITLE
Bug in supporting ICOM7100 station

### ISSUE THREAD

**Issue by Nokia808** [drowe67/freedv-gui#696] opened 2024-03-07 17:30 UTC
Hello. 

I re-installed FreeDV from official Fedora repositories. I'm on Fedora 38 X64 bit. FreeDV version is 1.8.4

1) I set my ICOM7100 as following:
setting > Connectors:
- DATA MODE: we set at "USB"
- CI-V: we leaved "CI-V Baud Rate" at "auto" (there are 2 options, "auto" & 19200, we kept it at default "auto")
- USB2/DATA1 Function > we set "DATA 1 Function" at "DV Data". Also, we set "DV Data/GPS Out Baud" at "9600"
- VSEND Select: we set at "OFF"
- 9600 bps Mode: we set at "ON"

2) I set ICOM7100 on "DATA" mode & connected it to my laptop by USB using USB version 2.0 port of laptop.

3) on program side
a. I configured audio perfectly with assistant of Walter/K5WH. Many thanks to him for supporting me.
b. The problem is in setting of PTT: in PTT configuration I set as following:
- selected "Use HAMlib PTT"
- Serial Device: "dev/ttyUSB0"     (there is NO COM port in list on linux. "dev/ttyUSB0 is the correct port)
- Serial rate: 9600      (we activated 9600 bps mode in ICOM7100, & we changed "DV Data/GPS Out Baud" from default 4800 to 9600 in setting of ICOM7100)
- Radio address: by default it is 88h. Program never accept to enter more than 2 elements & the 2 element must be number (never accept letter). I tried to edit it by ICOM7100 but never reached to "00" or any value composed from 2 numbers. After consulting Walter/K5WH about this he asked me to enter only 88. I did but PTT never worked & I received the following error message:

![freeDV-error](https://github.com/drowe67/freedv-gui/assets/25375330/36c869a3-8607-4993-9bd9-9e95e1255f23)

Please your kind help ! 

I feel that there is internal error in program in it's support for ICOM7100 ....

**Comment by tmiw** [comment] 2024-03-07 18:08
Actually, 9600bps mode isn't needed for FreeDV and should be set to OFF. That setting is intended more for higher speed data modes on VHF/UHF (for example, VARA FM).

Also, I'd try 19200 for "Serial Rate" in FreeDV given that seems to be the only option available on the 7100. Do VFO/mode adjustments get reflected in the user interface (and vice versa) with the current settings, or is it just PTT that's failing?

**Comment by Nokia808** [comment] 2024-03-07 18:38
1) Dear you asked me to use 19200 for serial rate. Which sector of setting you mean, I should set at 19200 ? We have:
- CI-V: which has "CI-V Baud Rate" that has 2 options, "auto" & 19200.
& we have:
- USB2/DATA1 Function > which has "DV Data/GPS Out Baud".

Which of above 2 I should set at 19200 in station setting before I set 19200 in FreeDV program PTT configuration ? One of them ? Both of them ?

2) you commented by the following: "Actually, 9600bps mode isn't needed for FreeDV" .... Do I need to turn it OFF or can I leave it ON without problems for FreeDV ?

**Comment by Nokia808** [comment] 2024-03-07 19:51
Okay. I feel that I will, finally, will get FreeDV working on my system.

But, there is one question you did not answered:
"DV Data/GPS Out Baud" was set by default on 4800, but we changed it to 9600. Do we need to revert it to 4800 ??

Thank you for your support !

**Comment by tmiw** [comment] 2024-03-07 22:20
> But, there is one question you did not answered: "DV Data/GPS Out Baud" was set by default on 4800, but we changed it to 9600. Do we need to revert it to 4800 or set it at value other than 4800 & 9600 ? Do we need to set it at 12900 ?

Shouldn't need to revert, but it might be a good idea to set it back to 4800 in case you use some other app in the future that needs the GPS.

**Comment by Tyrbiter** [comment] 2024-03-07 23:05
As a Fedora user I would say that the distro version of hamlib (4.5.5) is a year old and hamlib 4.6, although not released, has had a lot of development work done on it in that time.

**Comment by tmiw** [comment] 2024-03-07 23:32
> As a Fedora user I would say that the distro version of hamlib (4.5.5) is a year old and hamlib 4.6, although not released, has had a lot of development work done on it in that time.

As 4.6 is still "beta" I'd actually advise not to, especially since the project has had bad experiences trying to use it for the Windows and macOS builds in the past. That said, if it turns out that 4.6 does fix the problem that @Nokia808 is having, by all means use it.

**Comment by Nokia808** [comment] 2024-03-08 04:23
@tmiw 

You said about "DV Data/GPS Out Baud", that I "shouldn't revert it back to 4800".
Only one question about this: does "DV Data/GPS Out Baud" = 9600 is ideal for FreeDV or it is not related by any way to FreeDV ? 

In fact other Iraqi HAM radio operator assist me to set values on ICOM7100 & he has no previous experience with FreeDV, but he is only FT8 user & select values according to his experience with FT8 hopping that it will be same of FreeDV.

If I succeed to run FreeDV on my Fedora Linux, I will be 1st Iraqi HAM station using this mode & for that we have very poor knowledge with this mode ....

**Comment by Tyrbiter** [comment] 2024-03-08 13:58
On the IC7100 the DV mode means D-STAR, so this is not used for freedv. You are correct, you need the DATA mode and you need to ensure that the receive and transmit audio is provided via the USB connection.

Tx attenuation controls the amplitude of the modulated audio signal generated by freedv, this is just like the effect of varying the microphone output level on SSB, it controls the RF power level.

GPS/DV data output baud rate is unimportant for freedv.

The only receive signal report that matters for freedv is SNR, signal:noise ratio, which is shown in the freedv main window. You should be able to find the minimum SNR for difference modes in the freedv user manual. freedv is intelligible at 10% bit error rate but speech quality will not be at its best until the bit error rate reduces towards 1-2%.

**Comment by Tyrbiter** [comment] 2024-03-08 14:33
> As 4.6 is still "beta" I'd actually advise not to, especially since the project has had bad experiences trying to use it for the Windows and macOS builds in the past. That said, if it turns out that 4.6 does fix the problem that @Nokia808 is having, by all means use it.

I'm currently on my 385th build of hamlib-4.6~git and apart from a couple of broken versions I have had no problem with my TS-890 or IC-7300. But of course, others mileage may vary :)

There was to be a hamlib-4.5.6 but Mike cancelled it as 4.6 was diverging too far from the hamlib-4.5 codebase.

**Comment by Nokia808** [comment] 2024-03-08 18:13
Thank you very much ! Every thing now is clear ! It is the time to make real QSO by FreeDV !

Many thanks for all who help me ! I'm the 1st person in Iraq who transmit using this mode, & I hope to be who made 1st QSO by it.

**Comment by tmiw** [comment] 2024-03-08 19:03
> Tx attenuation controls the amplitude of the modulated audio signal generated by freedv, this is just like the effect of varying the microphone output level on SSB, it controls the RF power level.

I'll add that FreeDV behaves like other digital modes in that your ALC should not show any indication when you're transmitting. If it does show any, the TX Attenuation lets you adjust the output volume downward without affecting any other applications.

> Thank you very much ! Every thing now is clear ! It is the time to make real QSO by FreeDV !
> 
> Many thanks for all who help me ! I'm the 1st person in Iraq who transmit using this mode, & I hope to be who made 1st QSO by it.

Glad to help! And hopefully you'll be able to have a lot of FreeDV QSOs to come :) I'll go ahead and close this for now, but definitely feel free to open another issue if you run into further problems with the FreeDV application.

**Closed by tmiw** 2024-03-08 19:03 UTC

**Comment by Nokia808** [comment] 2024-03-08 19:28
@tmiw 
Can you, kindly, elaborate more on the following point:

I'll add that FreeDV behaves like other digital modes in that your ALC should not show any indication when you're transmitting. ......"

I inspected ACL meter when I activated advanced monitor screen that showing Power+VSWR+Currency+Voltage+Temperature+Compression+ALC. The ALC pointer was showing a level that DO NOT CROSS set limit that station on it by default. So, what you mean by "not show any indication" !! Do you indication that there is cross above limit that station set on it or you meant that ACL meter should be at ZERO level during transmitting ?

**Comment by Tyrbiter** [comment] 2024-03-08 23:19
ALC indication and the effect on the transmitted signal is different depending on the radio in use. I don't know the IC-7100 ALC characteristics, but I do know that ALC has very little effect on the IC-7300 transmit signal quality when using FT-8. 

freedv is more tolerant because it still works at higher bit error rates, but you can try the effect of decreasing output power using the Tx attenuation control, less power will mean less ALC action, and see if the BER improves.

On your question about the IC-7100 and running at high output power, this is a comment from a GM4 station who uses one:

"The IC-7100 was designed with FM and DStar operation in mind. It has good cooling and an effective fan. This means that it is very happy with high duty cycle work, and data seems to pose it few problems"

Of course it may be a hotter location where you are, Scotland is rarely hot.

**Comment by tmiw** [comment] 2024-03-09 03:50
> you meant that ACL meter should be at ZERO level during transmitting ?

Generally the ALC should show as zero. Of course, there are exceptions depending on the radio as @Tyrbiter mentioned (for example, Elecraft recommends something like 3-4 bars of ALC on the the KX2/KX3). If unsure, you can also set TX Attenuation to the lowest possible value and then gradually increase it until the power meter on your radio stops increasing.
