### ISSUE TITLE
ModuleNotFoundError: No module named 'radae_txe'

### ISSUE THREAD

**Issue by ekk11** [drowe67/freedv-gui#757] opened 2024-10-21 13:24 UTC
X-Ubuntu 24.04 (noble)

freedv-gui-2.0.0-20241018/build_linux/src$ ./freedv
Using RADE API version 1
[2024-10-21 15:07:01] [connect] Successful connection
[2024-10-21 15:07:01] [connect] WebSocket Connection [2602:fffa:fff:108a:216:3eff:fe32:ba39]:80 v-2 "WebSocket++/0.8.2" /socket.io/?EIO=4&transport=websocket&t=1729516021 101
model file: TBD
import_array returned: 0
ModuleNotFoundError: No module named 'radae_txe'
Error: importing radae_txe

#Looks for missing python-paths.

**Comment by tmiw** [comment] 2024-10-21 13:46
We're focused more on Windows at the moment but it is definitely possible to run it on Linux. Can you check out https://github.com/drowe67/freedv-gui/pull/758/files and let me know if those instructions work for you?

**Comment by tmiw** [comment] 2024-10-21 13:48
Actually, this is a duplicate of https://github.com/drowe67/freedv-gui/issues/749. Please add additional comments over there, thanks!

**Closed by tmiw** 2024-10-21 13:48 UTC
